export const ErrorCodes = {
	INTERNAL_ERROR: "INTERNAL_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	NOT_FOUND: "NOT_FOUND",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	CONFLICT: "CONFLICT",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	BAD_REQUEST: "BAD_REQUEST",
	SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
	ECONT_BAD_REQUEST: "ECONT_BAD_REQUEST",
	ECONT_AUTH_FAILED: "ECONT_AUTH_FAILED",
	ECONT_RATE_LIMITED: "ECONT_RATE_LIMITED",
	ECONT_UPSTREAM_UNAVAILABLE: "ECONT_UPSTREAM_UNAVAILABLE",
	ECONT_UPSTREAM_ERROR: "ECONT_UPSTREAM_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
